### ISSUE TITLE
Todo Plugins

### ISSUE THREAD

**Issue by nikogu** [umijs/plugins#1]
- [ ] script
- [ ] style
- [ ] favicon
- [ ] antd
- [ ] antdpro
- [ ] dva
- [ ] mf (micro fontend intl)
- [ ] i18n (i18n intl)
- [ ] react
- [ ] request
- [ ] router
- [ ] axios
- [ ] styled

**Comment by sorrycc** [comment]
我的想法，

* script 和 style 用复数，在集成到 preset 或框架里时根据 singular 的配置决定是否用单数的 key
* antd 和 antd-pro 我觉得可以合，包含 antd-mobile
* mf 先不集成，用 umi-plugin-qiankun，这个比较复杂，发展差不多了再集成进来
* i18n 是重写还是用 umi-plugin-locale? 
* react、request、router、axios 和 styled 分别是干啥？介绍下？

**Comment by nikogu** [comment]
@sorrycc  umi-plugin-locale 和 i18n 其实是两个插件，用法不一样，我们 i18n 这边是基于外网的 must + i18n.get 的方式

**Comment by nikogu** [comment]
i18n、mf、react、request、router、axios 和 styled  可以先放到 smallfish 里面，其他的可以放进来。
