### ISSUE TITLE
[plugin-model] model 中引用其他model时显示语法错误

### ISSUE THREAD

**Issue by leftstick** [umijs/plugins#107]
复现repo: [umi-model-issue](https://github.com/leftstick/umi-model-issue).

是这样的，在一个model`useMessageModelHasError.ts`，引用另一个model的值，如下：

```typescript
import { useCallback } from 'react';
import { useModel } from 'umi';

export default function useMessageModel() {
  const { title } = useModel('useAppModel');

  const sayHiError = useCallback(() => {
    console.log('error hello ', title);
  }, [title]);

  return {
    sayHiError,
  };
}
```

会有如下错误提示：

<img width="1086" alt="Screen Shot 2020-03-17 at 23 19 13" src="https://user-images.githubusercontent.com/1059956/76871206-be4f9300-68a5-11ea-8665-486402f5deb0.png">

> 'title' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)

但是，功能一模一样的代码，`useMessageModel.ts`，不直接用解构语法，改成如下这样：

```typescript
import { useCallback } from 'react';
import { useModel } from 'umi';

export default function useMessageModel() {
  const model = useModel('useAppModel');

  const { title } = model;

  const sayHi = useCallback(() => {
    console.log('hello ', title);
  }, [title]);

  return {
    sayHi,
  };
}
```

就没错了。

而且即便是上面报语法错误的写法，也已经可以正确运行，始终没理解这个错误的原因是什么

**Comment by tli4** [comment]
之前也有遇到过这个问题，同样的代码在不同的机器上 ts 推断的行为还不太一致。因为 TS 一直没有定位类型推导是 safe 或者是 sound 的，从不解构是可以拿到类型，解构之后就拿不到了。感觉更像是 ts 的 bug。目前推测是当数据类型足够复杂的时候，ts 会放弃自动推导类型，fallback 成 any.

一些 workarounds：
1. 协助 ts 推断出 useModel 的返回类型，例如：
`const { title } = useModel<'useAppModel'>('useAppModel');` 
2. 类型 cast:
```ts
import { useModel, Models } from 'umi';

export default function useMessageModel() {
  const { title } = useModel('useAppModel') as Models<'useAppModel'>;
}
```

**Comment by leftstick** [comment]
> 之前也有遇到过这个问题，同样的代码在不同的机器上 ts 推断的行为还不太一致。因为 TS 一直没有定位类型推导是 safe 或者是 sound 的，从不解构是可以拿到类型，解构之后就拿不到了。感觉更像是 ts 的 bug。目前推测是当数据类型足够复杂的时候，ts 会放弃自动推导类型，fallback 成 any.
> 
> 一些 workarounds：
> 
> 1. 协助 ts 推断出 useModel 的返回类型，例如：
>    `const { title } = useModel<'useAppModel'>('useAppModel');`
> 2. 类型 cast:
> 
> ```ts
> import { useModel, Models } from 'umi';
> 
> export default function useMessageModel() {
>   const { title } = useModel('useAppModel') as Models<'useAppModel'>;
> }
> ```

如下指定一下类型也行，就是觉得有点烦。。。

```typescript
import { useModel } from 'umi';

export default function useMessageModel() {
  const { title }: { title: string } = useModel('useAppModel');
}
```


那就先这样吧，似乎也没什么更秒的方案了
