### ISSUE TITLE
plugin-request依赖antd的组件，不装antd会造成无法使用

### ISSUE THREAD

**Issue by williamnie** [umijs/plugins#128]
plugin-request依赖antd的message, notification组件，如果不装antd，或造成插件无法使用，作为一个单独插件来说，设计上不要太依赖antd吧，没法做到通用。如果必须引用，用户的是antd-mobile，request error的组件是否要换成mobile端的呢？plugin-antd是内置了antd和antd-mobile,这里是否要做切换？

**Comment by yutingzhao1991** [comment]
嗯，有道理。应该是可以支持自定义。

```js
// 构建时配置
request: {
  antd: false,
}
```

然后可以在运行时自定义错误处理：

```
// app.ts
const request = {
  errorMessageHandler: () => {},
};
```

感兴趣来个 PR 吗？

**Comment by williamnie** [comment]
> 嗯，有道理。应该是可以支持自定义。
> 
> ```js
> // 构建时配置
> request: {
>   antd: false,
> }
> ```
> 
> 然后可以在运行时自定义错误处理：
> 
> ```
> // app.ts
> const request = {
>   errorMessageHandler: () => {},
> };
> ```
> 
> 感兴趣来个 PR 吗？

有兴趣，哈哈，我看看能不能写出来，擅长写不正经的代码🤣，

**Comment by williamnie** [comment]
> 嗯，有道理。应该是可以支持自定义。
> 
> ```js
> // 构建时配置
> request: {
>   antd: false,
> }
> ```
> 
> 然后可以在运行时自定义错误处理：
> 
> ```
> // app.ts
> const request = {
>   errorMessageHandler: () => {},
> };
> ```
> 
> 感兴趣来个 PR 吗？

尴尬的是，我不会写ts🤣

**Comment by feibi** [comment]
确实应该去掉antd依赖

**Comment by baranwang** [comment]
我试图用 alias 方法解决这个问题
```
  alias: {
    'antd/es/message': path.resolve(__dirname, './src/empty.js'),
    'antd/es/message/style': path.resolve(__dirname, './src/empty.js'),
    'antd/es/notification': path.resolve(__dirname, './src/empty.js'),
    'antd/es/notification/style': path.resolve(__dirname, './src/empty.js'),
  },
```
不过两个 style 部分不知道为什么没有效果

**Comment by baranwang** [comment]
暂时用了一个比较脏的方法，把 postinstall 钩子换个一个 shell

```
mkdir -p ./node_modules/antd/es/message
echo 'module.exports = {}' | tee -a ./node_modules/antd/es/message/index.js ./node_modules/antd/es/message/style.js
mkdir -p ./node_modules/antd/es/notification
echo 'module.exports = {}' | tee -a ./node_modules/antd/es/notification/index.js ./node_modules/antd/es/notification/style.js

npx umi generate tmp
```
