### ISSUE TITLE
plugin-layout、plugin-initial-state、plugin-access 三个插件结合使用问题

### ISSUE THREAD

**Issue by wangzou1995** [umijs/plugins#185]
1.plugin-initial-state中存放角色 ，
2.plugin-access 插件定义权限，
3.plugin-layout 渲染权限内相应菜单。
问题：当动态修改了plugin-initial-state中的角色后，plugin-layout插件会渲染出相应的菜单，但是点击菜单后会出现 403 无权限访问页面。plugin-layout源码index.tsx中定义了layoutConfig 变量，是否应该修改成当plugin-initial-state中的属性发生变化时会触发重新更新layoutConfig？

**Comment by xiaohuoni** [comment]
https://github.com/umijs/plugins/pull/183 已修复，等待发包
