### ISSUE TITLE
umi3 使用 plugin-qiankun 时 runtimePlugin.js 内的apps 为undefined

### ISSUE THREAD

**Issue by ThomasLiu** [umijs/plugins#190]
尝试使用 umi3 + qiankun 做微前端， 然后模仿 [plugins 内的 plugin-qiankun/examples](https://github.com/umijs/plugins/tree/master/packages/plugin-qiankun/examples)  来搭 master，但是运行后在 `runtimePlugin.js` 内的 `apps` 为 **undefined** 

![image](https://user-images.githubusercontent.com/3435615/80963054-cf963400-8e40-11ea-8b26-cd6b3fdbdc35.png)

在chrome内调试可以看到 [runtimePlugin.js](https://github.com/umijs/plugins/blob/master/packages/plugin-qiankun/src/master/runtimePlugin.ts) 内的 
```js
async function getMasterRuntime() {
  const config = plugin.applyPlugins({
    key: 'qiankun',
    type: ApplyPluginsType.modify,
    initialValue: {},
    async: true,
  });
  const { master } = config;
  return master || config;
}
```
这里的 `config` 为 **Promise** 对象

![image](https://user-images.githubusercontent.com/3435615/80962868-7201e780-8e40-11ea-9ade-5b8a977a4ca2.png)

[可重现最小仓库](https://github.com/ThomasLiu/qiankun_portal)

这里参考 [plugin-qiankun/examples/master/app.js](https://github.com/umijs/plugins/blob/master/packages/plugin-qiankun/examples/master/app.js)

```js
import request from './services/request';

export const qiankun = request('/apps').then(apps => ({ apps }));
```

.umirc.ts 的配置
```js
import { defineConfig } from 'umi';

export default defineConfig({
  analyze: {
    analyzerMode: 'server',
    analyzerPort: 8889,
    openAnalyzer: true,
    // generate stats file while ANALYZE_DUMP exist
    generateStatsFile: false,
    statsFilename: 'stats.json',
    logLevel: 'info',
    defaultSizes: 'parsed', // stat  // gzip
  },
  base: '/qiankun_portal/',
  hash: true,
  ignoreMomentLocale: true,
  nodeModulesTransform: {
    type: 'none',
  },
  publicPath: '/qiankun_portal/',
  routes: [{ path: '/', component: '@/pages/index' }],
  qiankun: {
    master: {
      defer: true,
      jsSandbox: true,
      prefetch: true,
    },
  },
  proxy: {
    '/api': {
      target: 'http://localhost:8000',
      changeOrigin: true,
    },
    '/api/app1': {
      target: 'http://localhost:8001',
      changeOrigin: true,
    },
    '/api/app3': {
      target: 'http://localhost:8002',
      changeOrigin: true,
    },
  },
});

```

**Comment by ThomasLiu** [comment]
重新试了一下，这次是把 plugins 内的 plugin-qiankun/examples 直接copy 出来，然后单独的 yarn，再yarn start，4个项目都跑起来，但是在chrome 上访问 8000 时，也是一样的问题。

奇怪的是，在 plugin 项目内，yarn 完，然后 build 了，再到 plugin-qiankun/examples 内 yarn start，examples 是跑得很正常的。

[可重现最小仓库](https://github.com/ThomasLiu/qiankun_test/tree/umi3)

在examples内的唯一改动是 `.umirc.js` 内的 plugins 都换成 `['@umijs/plugin-dva', '@umijs/plugin-antd', '@umijs/plugin-qiankun']`

```
export default {
  publicPath: '/app3/',
  outputPath: './dist/app3',
  mountElementId: 'app3',
  qiankun: {
    slave: {},
  },
  plugins: ['@umijs/plugin-dva', '@umijs/plugin-antd', '@umijs/plugin-qiankun'],
  // TODO 测试约定式路由
  routes: [
    { path: '/', exact: true, component: './index.js' },
    { path: '/:abc', component: './$abc.js' },
    { path: '/users', component: './user/index.js' },
  ],
  // TODO 测试 dynamicImport
  // dynamicImport: true,
};
```

**Comment by ThomasLiu** [comment]
下载了 umi 的源码 最终找到了 applyPlugins 的源码，在umi的项目packages/runtime/src/Plugin 的test中，对于参数为 `async: true` 得测试也是需要await 来调用。

然后把这里 改成
```js
async function getMasterRuntime() {
  const config = await  plugin.applyPlugins({
    key: 'qiankun',
    type: ApplyPluginsType.modify,
    initialValue: {},
    async: true,
  });
  const { master } = config;
  return master || config;
}
```

重新build 了一次，把生成的lib 复制到 项目的 `node_modules` 对应的文件夹后，就OK了(￣▽￣)

**Comment by ThomasLiu** [comment]
下载了 umi 的源码 最终找到了 applyPlugins 的源码，在umi的项目packages/runtime/src/Plugin 的test中，对于参数为 `async: true` 得测试也是需要await 来调用。

然后把这里 改成
```js
async function getMasterRuntime() {
  const config = await  plugin.applyPlugins({
    key: 'qiankun',
    type: ApplyPluginsType.modify,
    initialValue: {},
    async: true,
  });
  const { master } = config;
  return master || config;
}
```

重新build 了一次，把生成的lib 复制到 项目的 `node_modules` 对应的文件夹后，就OK了(￣▽￣)

**Comment by 7kms** [comment]
同样遇到这个问题.
请问这个版本的源码 `"@umijs/plugin-qiankun": "^2.2.0-0"`怎么看.  没有相应的tag. master分支的代码也对不上. 
有条件的话提个pr修复了吧.

**Comment by kuitos** [comment]
使用 ^2.3.0-6 或者重新 npm i @umijs/plugin-qiankun@next
