### ISSUE TITLE
[plugin-preact]: Cannot find module 'preact-compat/lib/create-react-class'

### ISSUE THREAD

**Issue by fjc0k** [umijs/plugins#192]
## 可能的原因

`plugin-preact` 的依赖只有 `preact`，没有 `preact-compat`，但对 `preact-compat` 的 alias 又是必须的。

**Comment by fjc0k** [comment]
@chenshuai2144 老哥，你这，删了依赖，代码里又有 preact-compat/lib/create-react-class，一安装这个插件，必报 Cannot find module 'preact-compat/lib/create-react-class'，有没有测试过哦。。。

**Comment by fjc0k** [comment]
```bash
yarn add preact
```

```javascript
  chainWebpack(config) {
    config.resolve.alias
      .set('react', 'preact/compat')
      .set('react-dom', 'preact/compat')
      .end()
  },
```

**Comment by chenshuai2144** [comment]
看commit回滚了
