### ISSUE TITLE
@umijs/plugins-layout   icon应该如何配置

### ISSUE THREAD

**Issue by ahayaSKBINCN** [umijs/plugins#197]
//pages
DashBoard.menu = {
    name: 'DashBoard',
    icon:'user'
}
//.umi/core/routes.ts
{
        "path": "/DashBoard",
        "exact": true,
        "component": require('@/pages/DashBoard/index.tsx').default,
        "menu": {
          "name": "DashBoard",
          "icon": "user"
        }
//浏览器里
userDashBoard ???
icon 并没有被处理 而是直接返回了字符串；
以下写法也并没有被umi识别处理
icon:（）=><Icon/>；
icon:Icon;
但是不使用icon 收起菜单的效果又很差 ；
想问问是不是我的写法上存在问题；

**Comment by xiaohuoni** [comment]
这个写法是有效的，确认一下你的 plugin-layout 版本
```
icon:'user'
```

**Comment by Mrminfive** [comment]
https://github.com/umijs/plugins/blob/984579e6828e95f3c763c00bff32e95024ebc090/packages/plugin-layout/src/index.ts#L107-L115
获取中 userConfig 中不包含约定式路由生成的 routes

**Comment by ahayaSKBINCN** [comment]
我在packages 里发现了上面的代码 但是很明显并没有起作用  
我的layout 版本是0.10.0 
node版本是 11.10.1
如果没有别的办法的话 我只有考虑 手动添加 prolayout 来实现 icons 加载
