### ISSUE TITLE
[plugin-model] 组件订阅某个 model 中的数据(数据类型为数组)，当该 model 中的数据更新后未 rerender 该组件

### ISSUE THREAD

**Issue by phobal** [umijs/plugins#215]
## What happens?

组件订阅某个 model 中的数据，当该 model 中的数据更新后未 rerender 组件

比如下面的示例  

当鼠标点击五角星的时候应该由空心变为实心才对，但是实际上并没有变化

![image](https://user-images.githubusercontent.com/9244211/82288959-3df8fb80-99d6-11ea-9793-1929047ced9b.png)

模型 `models/home.ts`

``` ts
import { useState, useEffect } from 'react';
import { useRequest } from 'umi';
import { query } from '@/services/api';
import { IFocusCustomer } from '@/types';

export default () => {
  const [focusUsers, setFocusUsers] = useState<IFocusCustomer[]>([]);
  const { data } = useRequest(query);
  useEffect(() => {
    setFocusUsers(data);
  }, [data]);
  return { focusUsers, setFocusUsers };
};

```

页面 `pages/index.tsx`

``` tsx
const UserItem = ({ id, name, isActive }) => {
  // @ts-ignore
  const { focusUsers, setFocusUsers } = useModel('home', (m) =>
    pick(m, 'focusUsers', 'setFocusUsers'),
  );
  // 点击五角星的逻辑
  const onClick = (status: string) => {
    const result = focusUsers.map((user: IFocusCustomer) => {
      if (user.id === id) {
        user.isActive = status !== 'active';
      }
      return user;
    });
    // 更新 model 中的数据
    setFocusUsers(result);
  };
  return (
    <>
      {isActive ? (
        <ActiveStarIcon onClick={() => onClick('active')} />
      ) : (
        <UnActiveStarIcon onClick={() => onClick('unActive')} />
      )}
      <Link to="" style={{ color: 'rgba(0, 0, 0, 0.5)' }}>
        {name}
      </Link>
    </>
  );
};

export default () => {
  // @ts-ignore
  const { focusUsers } = useModel('home', (m) => pick(m, 'focusUsers'));
  return (
    <List
      dataSource={focusUsers}
      renderItem={(item: IFocusCustomer) => (
        <List.Item>
          <UserItem id={item.id} name={item.customerName} isActive={item.isActive} />
        </List.Item>
      )}
    />
  );
};

```
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/phobal/useModel-demo

## 复现步骤，错误日志以及相关配置

见 demo 仓库中的 [如何启动](https://github.com/phobal/useModel-demo#%E5%A6%82%E4%BD%95%E5%90%AF%E5%8A%A8)

## 相关环境信息

- **Umi 版本**：3.1.1
- **Node 版本**：10.15.0
- **操作系统**：MacOS v10.14.4

**Comment by phobal** [comment]
初步定位到问题出在 https://github.com/umijs/plugins/blob/master/packages/plugin-model/src/utils/getUseModelContent.ts#L33
![image](https://user-images.githubusercontent.com/9244211/82289695-f2dfe800-99d7-11ea-9a6c-ed7dfcb8c2d9.png)
这里的 lastState 实际上为 currentState，所以在 _.isEqual 的时候，ret 和 lastState 始终是相等的了

困惑的点：
1、当 State 的数据类型为非数组时更新数据后组件会重新 render
2、当 State 的数据类型为数组的时候，更新数组，但 length 不变(实际数组对象的值变了)组件也不会重新 render

**Comment by tli4** [comment]
这里确实有问题，介意来个 PR 吗？需要一个空的 useEffect 记录 previousState

```js
useEffect(() => {
  lastState.current = state;
})
```

**Comment by phobal** [comment]
@tli4 PR https://github.com/umijs/plugins/pull/229
