### ISSUE TITLE
[BUG]按照官方使用antd-pro集成qiankun插件后，界面显示有问题，分为上下两层

### ISSUE THREAD

**Issue by koupeng** [umijs/plugins#230]
完整复现问题的代码库：
https://github.com/koupeng/and-design-pro-qiankun

![image](https://user-images.githubusercontent.com/6110684/82642939-486afd80-9c41-11ea-8dda-b3f4cee2b8e1.png)

**Comment by Lpmvb** [comment]
把 document.ejs 里的根节点 id 改成 root-slave 就好了

**Comment by koupeng** [comment]
谢谢，已经解决。
