### ISSUE TITLE
qiankun子应用IE11下兼容性问题

### ISSUE THREAD

**Issue by spiroo** [umijs/plugins#249]
子应用使用umi3.0插件umijs/plugin-qiankun@next，单独运行子应用，IE11下没有问题；通过主应用加载子应用，报错如下：
![image](https://user-images.githubusercontent.com/7858201/83939140-04652480-a80d-11ea-8184-4fde48dd8563.png)
qiankun版本2.0.5和2.0.11、2.0.12-0均有此问题。
请问是什么原因呢？

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/565
