### ISSUE TITLE
子应用如何把父应用传过来的值传递给自己的组件？？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/plugins#255]
![20200611163822](https://user-images.githubusercontent.com/16549630/84363984-10ccf100-ac02-11ea-8d1e-705cfbfa6646.jpg)
子应用可以拿到父应用传过来的值，但是如何将传过来的值传递给自己的组件呢？

**Comment by kuitos** [comment]
https://umijs.org/zh-CN/plugins/plugin-qiankun#%E7%88%B6%E5%AD%90%E5%BA%94%E7%94%A8%E9%80%9A%E8%AE%AF
