### ISSUE TITLE
qiankun多个子项目，只启动了一个，其他的没有启动会报错

### ISSUE THREAD

**Issue by Luxiaoshi** [umijs/plugins#259]
umi@3.2.3
@umijs/plugin-qiankun@^2.2.0

用的构建式
qiankun: {
    master: {
      apps: [
        {
          name: 'app1',
          entry: '//localhost:7001',
          base: '/app1',
          history: 'browser'
        }, {
          name: 'ods',
          entry: '//localhost:7002',
          base: '/ods',
          history: 'browser'
        }
      ],
      jsSandbox: true,
      prefetch: true
    }
  },
当只启动了7002，没有启动7001的时候，打开http://localhost:8000/ods,页面的console会报错
GET http://localhost:7001/ net::ERR_CONNECTION_REFUSED

![image](https://user-images.githubusercontent.com/8713879/84991452-1d5cc680-b179-11ea-83ab-8c8eb86f0f2c.png)

**Comment by phobal** [comment]
把 prefetch 设置为 false 试试

**Comment by Luxiaoshi** [comment]
@phobal 可以了，感谢
