### ISSUE TITLE
[plugin-qiankun]子应用配置文档（qiankun: {}）有误

### ISSUE THREAD

**Issue by ABoat365** [umijs/plugins#268]
# 文档内容
## 子应用
```
export default {
  base: `/${appName}`, // 子应用的 base，默认为 package.json 中的 name 字段
  qiankun: { slave: {} },
};
```
如果子应用配置项为空，即 slave: {}，则可以省略配置：
```
export default {
  base: `/${appName}`, // 子应用的 base，默认为 package.json 中的 name 字段
  qiankun: {},
};
```
# 问题
如果子应用配置项为空，即 slave: {}，不可以省略配置，否则会报错！
![22B29313-09E1-4ee0-931E-E2B3B90552D7](https://user-images.githubusercontent.com/34494887/85736449-14e42d00-b731-11ea-8ff7-e385f1d50657.png)

# 涉及版本（不完全测试）
2.2.0、2.1.1

**Comment by kuitos** [comment]
@umijs/plugin-qiankun v2.3.2

**Comment by Valar103769** [comment]
我都没看到配置项, 还在思考怎么配置baseroute呢 cao
