### ISSUE TITLE
[plugin-qiankun]: 子应用集成Ueditor后全局变量问题

### ISSUE THREAD

**Issue by Lpmvb** [umijs/plugins#277]
问题：
![image](https://user-images.githubusercontent.com/34727913/86094643-626eea00-bae3-11ea-86ad-1e72fb8bc628.png)

子项目集成了Ueditor，通过静态资源的方式引入源码，主项目中加载不到 Ueditor 的全局变量，导致出现一些问题。

最小可复现项目：https://github.com/Lpmvb/qiankun-test

**Comment by kuitos** [comment]
子应用是沙箱隔离的，主应用获取不到子应用泄露的全局变量是符合预期的。
如果你一定要泄露出来，可以把沙箱关掉（不建议）

**Comment by Lpmvb** [comment]
那么类似这样的问题只能通过关掉沙箱解决吗

**Comment by Lpmvb** [comment]
关掉沙箱也解决不了问题

**Comment by kuitos** [comment]
1. 关沙箱可以解决变量访问不到的情况
2. 配置 ueditor `UEDITOR_HOME_URL: '//localhost:7002/app1/neditor/'`
