### ISSUE TITLE
子应用组件获取不到父应用通过useModel传递过来的值？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/plugins#281]
主应用采用umi脚手架构建，子应用使用antd proV4
子应用获取不到主应用传递过来的值，按照文档使用useModel传值。采用的是路由绑定式加载子应用的

主应用与子应用umi，@umijs/plugin-qiankun版本一致：
umi：3.2.6
@umijs/plugin-qiankun：2.3.1

相关代码配置如下：

`

// 主应用配置 根目录：app.js
export const useQiankunStateForSlave = () => {
  const [ globalState, setQiankunGlobalState ] = useState({
    slogan: 'Hello MicroFrontend',
  });

  return {
    globalState,
    setQiankunGlobalState,
  };
};
// 子应用组件里设置
import { connect ,useModel } from "umi";

const  Welcome = props =>{
  console.info(props);
  const { globalState } = useModel('@@qiankunStateFromMaster') || {}
  console.info(globalState); // 报undefined
  return (
    <>
      <p>主应用传过来的值是：{ globalState }</p>
    </>
  )
}

export default connect(({ welcome, loading  }) => ({
  welcome: welcome,
  loading,
}))(Welcome);
`
可复现仓库地址：https://github.com/zhilianbi520/qiankundemo

**Comment by kuitos** [comment]
你这都还是用的老的方式啊🤪 https://github.com/zhilianbi520/qiankundemo/blob/master/ParentApplication/.umirc.ts#L41

看升级公告 https://umijs.org/plugins/plugin-qiankun#%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97
