### ISSUE TITLE
[plugin-qiankun]关于qiankun的nginx部署问题

### ISSUE THREAD

**Issue by Luxiaoshi** [umijs/plugins#282]
想请教一下大家都是如何部署qiankun的父子项目的。
我目前的想法是父项目配一个路由地址，如 a.test.com
子项目配一个，如 b.test.com
然后修改父项目的entry: '//localhost:7001',为b.test.com
但是这样的话不是还需要维护一份dev的qiankun配置和生产的qiankun配置吗。
或者是否有其他更简单的方式

**Comment by Luxiaoshi** [comment]
还有个小问题，子项目配置了base的话，如何通过history跳转到父项目呢。

**Comment by zhilianbi520** [comment]
> 还有个小问题，子项目配置了base的话，如何通过history跳转到父项目呢。

同想问这个问题，当前进入子应用后无法跳转回主应用～～

**Comment by Luxiaoshi** [comment]
没有大佬解决一下吗

**Comment by howel52** [comment]
> 但是这样的话不是还需要维护一份dev的qiankun配置和生产的qiankun配置吗

没必要两份，`isProd ? 'b.test.com' : 'localhost'` 这样应该就可以了？
