### ISSUE TITLE
[plugin-dva] 在umi@3中没有按需加载功能，是否有计划在未来支持

### ISSUE THREAD

**Issue by hurryhuang1007** [umijs/plugins#292]
如题， 如果有在计划支持， 可否给出个大概时间。
如果没有计划支持的话， 能否给一个最佳实现（例子）呢？

**Comment by sorrycc** [comment]
短期没有，按需加载是考虑尺寸问题吗？dva model 通常不会大吧。

**Comment by hurryhuang1007** [comment]
确实是尺寸问题， 因为我在model里引用了些比较大的依赖。
不过我现在使用import()来实现这些库的懒加载， 所以dva model没有懒加载也不是问题了。

**Comment by feibi** [comment]
> 短期没有，按需加载是考虑尺寸问题吗？dva model 通常不会大吧。

没有按需加载，权限路由无法阻止history.listen中的请求，有其他方案吗

**Comment by hurryhuang1007** [comment]
你好 我又来了。 还是那个问题， 因为我现在做的是个electron客户端产品， 然后会有一个主窗口 若干辅助窗口，dva其实只在主窗口中有使用到， 辅助窗口的加载其实是多余的。

随着dva的model里的代码越来越多，调用其他模块的方法也越来越多， 然后其他模块又调用了别的模块的代码。 对辅助窗口的打开速度产生了一点影响，所以我又回来解决这个问题了。
我看了下dva插件的实现，是围绕着umi抛出的插件api写的， 和传统的dva项目天差地别。 所以我现在想要实现在特定窗口(页面)加载特定的model也要围绕umi的插件api写吗？

**Comment by hurryhuang1007** [comment]
> 你好 我又来了。 还是那个问题， 因为我现在做的是个electron客户端产品， 然后会有一个主窗口与若干辅助窗口，dva其实只在主窗口中有使用到， 辅助窗口的加载其实是多余的。
> 
> 随着dva的model里的代码越来越多，调用其他模块的方法也越来越多， 然后其他模块又调用了别的模块的代码。 对辅助窗口的打开速度产生了一点影响，所以我又回来解决这个问题了。。
> 我看了下dva插件的实现，是围绕着umi抛出的插件api写的， 和传统的dva项目天差地别。 所以我现在想要实现在特定窗口(页面)加载特定的model也要围绕umi的插件api写吗？

我认真看了下dva的文档， 其中有说到怎么动态加载model。 但是我认真想了下，还是 只在主窗口加载并使用dva。 请问下，这可以实现吗？可以提供个思路吗

**Comment by 1999hk** [comment]
多页面应用使用吗，路由二次封装实现有案例不，大佬

**Comment by hurryhuang1007** [comment]
> 多页面应用使用吗，路由二次封装实现有案例不，大佬

我是直接用的umi 然后路由是用的hash路由

**Comment by yuanguandong** [comment]
> > 多页面应用使用吗，路由二次封装实现有案例不，大佬
> 
> 我是直接用的umi 然后路由是用的hash路由

看你关闭了这个issue，想问下你是怎么解决的，我的问题和你类似，虽然model文件不大，但是数量非常多，首屏加载几百个model很耗时

**Comment by duanbaosheng** [comment]
> > > 多页面应用使用吗，路由二次封装实现有案例不，大佬
> > 
> > 
> > 我是直接用的umi 然后路由是用的hash路由
> 
> 看你关闭了这个issue，想问下你是怎么解决的，我的问题和你类似，虽然model文件不大，但是数量非常多，首屏加载几百个model很耗时

看了一下  目前应该没有很好的解决办法
