### ISSUE TITLE
[plugin-qiankun] umi history.push 或者 Link 跳转的时候会重复跳转两次路由

### ISSUE THREAD

**Issue by Lpmvb** [umijs/plugins#297]
问题：umi history.push 或者 Link 跳转的时候会重复跳转两次路由
版本:
        "@umijs/plugin-qiankun": "^2.4.1",
        "umi": "^3.2.7",
最小复现仓库：https://github.com/Lpmvb/qiankun-test ，在主项目中点击跳转，可看到通过 dva 监听到的 history 跳转了两次

**Comment by songning0605** [comment]
是的，我也遇到了这个问题，browser模式下会这样，hash模式下就没问题
