### ISSUE TITLE
hideNav 无效 

### ISSUE THREAD

**Issue by leesama** [umijs/plugins#300]
今天看见最新版本修复了该问题，重装依赖后，发现原本正常的chrome也无效了。

**Comment by leesama** [comment]
@chenshuai2144

**Comment by nylqd** [comment]
同样的问题+1 hideMenu失效

**Comment by maidiwen** [comment]
同样遇到这个问题。😔

**Comment by leesama** [comment]
Umi文档更新了，设置layout false 可隐藏。具体可以查下类似的issue
