### ISSUE TITLE
useModel('@@qiankunStateForSlave') undefined

### ISSUE THREAD

**Issue by mmerina** [umijs/plugins#303]
主应用的全局state变化在子应用注册前，导致子应用获得的props没有更新

想尝试手动触发更新，useModel('@@qiankunStateForSlave') 报undefined

**Comment by tli4** [comment]
`src/app.ts` 里有导出 `useQiankunStateForSlave` 吗？

**Comment by yanzhandong** [comment]
@ttys026 pro  v4版本里 没有app.ts 在哪里设置导出
