### ISSUE TITLE
umi-plugin-qiankun

### ISSUE THREAD

**Issue by JeremKeith** [umijs/plugins#320]
你好，想问一下约定式路由的情况下，如何配置qiankun的子应用。

**Comment by Mu-xue** [comment]
通过umi3扩展路由属性的方式，在pages下的app1.tsx文件里，设置`Component.microApp = 'app1';`

https://umijs.org/zh-CN/docs/convention-routing#%E6%89%A9%E5%B1%95%E8%B7%AF%E7%94%B1%E5%B1%9E%E6%80%A7
