### ISSUE TITLE
plugin-layout 导致antd icons 全量导入

### ISSUE THREAD

**Issue by Nokecy** [umijs/plugins#325]
#168
https://github.com/umijs/plugins/blob/c1d0b3b8048f8559e86085e209ed0e387746f391/packages/plugin-layout/src/index.ts#L3

**Comment by Nokecy** [comment]
单独使用pro-layout 没有问题，通过umi的layout插件引用pro-layout 就会出现问题。大小相差快1M
![image](https://user-images.githubusercontent.com/12318131/89992997-aba48300-dcb8-11ea-94cf-514e3bb7d8d2.png)

_Originally posted by @Nokecy in https://github.com/ant-design/pro-components/issues/163#issuecomment-672730079_

**Comment by chenshuai2144** [comment]
这个不是 runtime 的应该不会全部编译吧

**Comment by Nokecy** [comment]
不确定是不是这里的问题 ，单独使用pro-layout 不会出现这个问题。使用umi layout插件引入就会出现。。
