### ISSUE TITLE
qiankun子应用的url请求问题

### ISSUE THREAD

**Issue by KellenHe** [umijs/plugins#327]
目前我的主应用是angular，端口为4200，
子应用是react并使用了@umijs/plugin-qiankun，端口为8000。

加载后子应用会请求http://localhost:4200/dev-server/info，
这个是在子应用的8000端口上，请问如何修改这个url信息？

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/315
