### ISSUE TITLE
useModel 单元测试出错。

### ISSUE THREAD

**Issue by xiaorong61** [umijs/plugins#337]
import { renderHook, act } from '@testing-library/react-hooks';
![image](https://user-images.githubusercontent.com/5251387/90762906-64516e80-e318-11ea-8967-9c26986b7522.png)

**Comment by ttys026** [comment]
测试时需要使用 provider 包裹，参照：
https://github.com/umijs/plugins/blob/99636ca5bdfdc47c519e37bd4aef3cbbb7a2edae/packages/plugin-model/tests/index.test.tsx#L56
