### ISSUE TITLE
更新preset-react，models中文件名称带'-'会报错

### ISSUE THREAD

**Issue by yaoguoba** [umijs/plugins#339]
error  in ./src/.umi/plugin-dva/dva.ts

Syntax Error: SyntaxError: D:\Works\fy-mall\fy-mall-web\src\.umi\plugin-dva\dva.ts: Unexpected token (15:19)

  13 | import Modellogin from 'D:/Works/fy-mall/fy-mall-web/src/models/login.ts';
  14 | import Modelmenu from 'D:/Works/fy-mall/fy-mall-web/src/models/menu.ts';
> 15 | import Modeloperate-log from 'D:/Works/fy-mall/fy-mall-web/src/models/operate-log.ts';

operate-log.ts 这种文件名不支持，删除'-'之后，好了

**Comment by sorrycc** [comment]
是 bug，我修下。

**Comment by sorrycc** [comment]
Fixed.

[1/2] Publish package @umijs/plugin-dva
+ @umijs/plugin-dva@0.8.2
[2/2] Publish package @umijs/preset-react
+ @umijs/preset-react@1.6.2
