### ISSUE TITLE
执行yarn之后，控制台报错

### ISSUE THREAD

**Issue by Plortinus** [umijs/plugins#343]
yarn 之后，执行`umi g tmp`会报下面的错，好像是@umijs/plugin-antd升级造成的
`$ umi g tmp
api.addDepInfo is not a function
TypeError: api.addDepInfo is not a function
`

**Comment by sorrycc** [comment]
umi 不要锁死版本，一起升。

**Comment by peterzhai** [comment]
umi3.2.3还是报这个错
