### ISSUE TITLE
0.8.1找不到了？

### ISSUE THREAD

**Issue by qld-cf** [umijs/plugins#344]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @umijs/plugin-dva@0.8.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@umijs/preset-react'
npm ERR! notarget

**Comment by sorrycc** [comment]
https://unpkg.com/browse/@umijs/plugin-dva@0.8.1/
有的。
