### ISSUE TITLE
安装@umijs/plugin-qiankun插件后，无法import MicroApp

### ISSUE THREAD

**Issue by ntfs32** [umijs/plugins#345]
版本“
@umijs/plugin-qiankun@2.9.1
umi@3.2.16

✔ Webpack
  Compiled successfully in 47.91s

 WARNING  Compiled with 1 warnings                                                                                              3:23:02 ├F10: PM┤

 warning  in ./src/app.js

"export 'MicroApp' was not found in 'umi'

  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)

**Comment by sorrycc** [comment]
@umijs/plugin-qiankun@2.8.x 无此问题？

**Comment by ntfs32** [comment]
> @umijs/plugin-qiankun@2.8.x 无此问题？

{master: {apps: []}} 配置增加没有问题了，没有注册上插件master 就没有 MicroApp组件，谢谢
