### ISSUE TITLE
[Bug] Removing extra whitespace in SelectLang

### ISSUE THREAD

**Issue by truongces** [umijs/plugins#346]
Vietnamese (vi-VN) has an extra space in the object defaultLangUConfigMap. 
Thank you.

**Comment by sorrycc** [comment]
How to reproduce?

**Comment by truongces** [comment]
Please check the template line 354 & 355
https://github.com/umijs/plugins/blob/master/packages/plugin-locale/src/templates/SelectLang.tpl

**Comment by truongces** [comment]
Btw, kindly update the icon, it's not the Vietnam flag. Thank you.
