### ISSUE TITLE
qiankun控制台警告 使用的是path-to-regexp v6

### ISSUE THREAD

**Issue by hengkx** [umijs/plugins#357]
in ./src/.umi/plugin-qiankun/common.ts
"export 'default' (imported as 'pathToRegexp') was not found in 'path-to-regexp'

**Comment by hengkx** [comment]
请问一下 什么时候 可以修复

**Comment by kuitos** [comment]
已经修复了，装最新版本

**Comment by hengkx** [comment]
装了 最新版本 并没有修复

**Comment by lynxerzhang** [comment]
同样遇到了这个问题
