### ISSUE TITLE
[plugin-request] 是否删除部分不通用的代码

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/plugins#371]
相关Issues : https://github.com/umijs/umi/issues/4813

https://github.com/umijs/plugins/blob/a5e823f356ef9f7c7f3d26192e6439a5254168cf/packages/plugin-request/src/request.ts#L149-L204 

感觉这部分代码，写在这里不太合适，错误码应该是需要和服务端约定的。错误的表现，应该是根据原有项目中的提示来使用。

**Comment by ycjcl868** [comment]
+1，这部分是糅合了

**Comment by ziyoung** [comment]
> @margitoxis 需要自定义只要重写覆盖一下 errorHandler 就可以。

这样操作也是会失败的，antd 的部分代码还是会打包进入。
我也不能设置 antd 为 false，否则样式全都没有了。
如果仅仅是修改 `.umirc` 中的 alias 也不生效，只能通过 chainWebpack 来调整。

查看代码，发现 plugin-request 注册个 alias。
https://github.com/umijs/plugins/blob/b77471f4d53ff4521dab34869d660c2911e04eaa/packages/plugin-request/src/index.ts#L63-L68

**Comment by ziyoung** [comment]
另外，L18 的注释可以删除了，有误导。😂
https://github.com/umijs/plugins/blob/dbfa31c46e57970405fa7cb444423340ed7ad416/packages/plugin-request/src/request.ts#L17-L20

**Comment by bobbychan** [comment]
> > @margitoxis 需要自定义只要重写覆盖一下 errorHandler 就可以。
> 
> 这样操作也是会失败的，antd 的部分代码还是会打包进去。
> 
> 我也不能设置 antd 为 false，否则样式全都没有了。
> 
> 如果仅仅是修改 `.umirc` 中的 alias 也不生效，只能通过 chainWebpack 来调整。
> 
> 查看代码，发现 plugin-request 注册个 alias。
> https://github.com/umijs/plugins/blob/b77471f4d53ff4521dab34869d660c2911e04eaa/packages/plugin-request/src/index.ts#L63-L68

请问如何使用chainWebpack来调整的呢？能否贴下代码，感谢！
