### ISSUE TITLE
主应用的@umijs/plugin-qiankun是2.x，子应用的是1.x，请问应该如何实现通讯

### ISSUE THREAD

**Issue by Mu-xue** [umijs/plugins#383]
qiankun2的通讯方式是用
`  const masterProps = useModel('@@qiankunStateFromMaster'); `

qiankun1则是用
`  const masterProps = useRootExports() `

怎么实现这2个应用间的通讯呀？

**Comment by kuitos** [comment]
基于 props https://umijs.org/plugins/plugin-qiankun#%E5%9F%BA%E4%BA%8E-props-%E4%BC%A0%E9%80%92
