### ISSUE TITLE
umi@2.8.7 使用umijs/plugin-qiankun 的问题

### ISSUE THREAD

**Issue by Chad97** [umijs/plugins#414]
- "@umijs/plugin-qiankun": "^2.16.0",
- "umi": "^2.8.7",

### 步骤
> 按照官方文档配置子应用 [url](https://umijs.org/zh-CN/plugins/plugin-qiankun#%E7%AC%AC%E4%B8%80%E6%AD%A5%EF%BC%9A%E6%B3%A8%E5%86%8C%E5%AD%90%E5%BA%94%E7%94%A8)

在注册 子应用的时候出现问题

a.  插件构建期配置子应用
无法构建，一直出现空白页

- code
```js
export default {
plugins: [
    ....
  [
    '@umijs/plugin-qiankun',
    {
      master: {
        defer: true, // 是否异步渲染
        jsSandbox: true, // 是否启用 js 沙箱
        prefetch: true, // 是否启用 prefetch 特性
        apps: [
          {
            name: 'app1', // 唯一 id
            entry: '//localhost:7001', // html entry
            base: '/app1/project', // app1 的路由前缀，通过这个前缀判断是否要启动该应用，通常跟子应用的 base 保持一致
            history: 'browser',
          },
          {
            name: 'app2', // 唯一 id
            entry: '//localhost:7002', // html entry
            base: '/app2/project', // app1 的路由前缀，通过这个前缀判断是否要启动该应用，通常跟子应用的 base 保持一致
            history: 'browser',
          },
        ],
      },
    },
  ],
  ]
}
```

b. 运行时动态配置子应用（src/app.ts 里开启）
配置放在 app.ts

报错

![image](https://user-images.githubusercontent.com/42793079/96698943-45c32e80-13c0-11eb-9590-1f848eeef324.png)

在umi2作为 master 的情况下如何使用 qiankun 呢？

**Comment by xuanxuan321** [comment]
同问

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/99037023-d0f9a380-25bd-11eb-8913-cc1b2bf4f2d0.png)
https://github.com/umijs/umi-plugin-qiankun
