### ISSUE TITLE
[plugin-qiankun] useModel 父子应用通信无法在切换应用时保持最新的全局数据

### ISSUE THREAD

**Issue by iwyvi** [umijs/plugins#426]
### 问题描述

根据我的理解，子应用中使用 `useModel('@@qiankunStateFromMaster')` ，获取到的应该是一份全局的数据，不会随着子应用切换而变化。

目前存在的问题是，每当子应用在重新挂载后，子应用获取到的这个值就会变成首次挂载时获取到的值

### 复现方式

目前最新 commit (e652620eee253e1b2aa10be9c7fb98be87d96f81)， plugin-qiankun 下运行 `yarn start`，下面介绍了两种复现方式：

1. 打开主应用 `http://localhost:8000/`，此时 Home 页面里的 app1 有 `globalState: {"slogan":"Hello MicroFrontend"}`，点击修改全局 state，Home 里的 app1 内修改为`globalState: {"slogan":"Hello Qiankun"}`，此时切换顶部导航到 app1 再切回 Home，Home 里的 app1 内又变成了 `globalState: {"slogan":"Hello MicroFrontend"}`

2. 直接打开 `http://localhost:8000/app1` ，此时页面内有 `globalState: {"slogan":"Hello MicroFrontend"}`，切换顶部导航到 Home，点击修改全局 state，再切回 app1，这里的 `globalState` 依然保持初始值不变，再切回 Home，这里的 `globalState` 也变回了初始值

### 问题原因

https://github.com/umijs/plugins/blob/e652620eee253e1b2aa10be9c7fb98be87d96f81/packages/plugin-qiankun/src/slave/qiankunModel.ts.tpl#L10

这里每次重新挂载子应用时都会从 initState 初始化，然而这个 initState 只在首次挂载才会被赋值，在之后切换过来时则直接作为 useState 的初始值，且二次切换时先触发了 `setModelState` 函数调用，之后子应用这个 hook 的 useState 才被初始化，因此每次切换回来都回到了初始值。

目前我通过对项目中生成的文件 `.umi/plugin-qiankun/qiankunModel` 做以下修改可以解决这个问题，但是我感觉这里可能是二次挂载的 `setModelState` 调用顺序的问题

```javascript
export default () => {
  const [state, setState] = useState(initState);
  setModelState =(val) => {
    initState = val;
    setState(val);
  };
  return state;
};
```

**Comment by wuhao930406** [comment]
遇到同样的问题，顶

**Comment by aoxiang78** [comment]
我也是一样的问题，不知道可有比较好的解决方案？ @iwyvi
