### ISSUE TITLE
[umi/qiankun] 路由使用通配符，没有重新渲染子应用？

### ISSUE THREAD

**Issue by DevXiaolan** [umijs/plugins#434]
路由配置

```
{
  path: '/app/:name',
  component: './mfe-container',
}
```

mfe-container.tsx

```
const params = useParams() as IParam;
const [name, ...url] = params.name.split('/');
console.log(name);
return <MicroAppWithMemoHistory
      name={name}
      url={`/${url.join('/')}`}
  />
```

app.ts  
```
export const qiankun = async () => {
  const apps = await getApps();
  return {
    apps,
  };
};
```

**Comment by DevXiaolan** [comment]
现象：

1. 首次点击菜单的子应用A ，console打印 ”A“，页面顺利渲染子应用A
2. 然后点击菜单子应用B，console打印”B“，页面没有变化，还是子应用A
3. 然后手动刷新页面，console打印 ”B“，页面顺利渲染子应用B


用我的话说，就是 **当使用通配符路由配置时，MicroAppWithMemoHistory 组件并不能重新加载子应用。**
MicroApp

**Comment by MoHuiTou** [comment]
我也遇到这个问题了，目前通过加不同元素的方式重新加载

```
return ( 
<div>
  <div>{name}</div>
  <MicroAppWithMemoHistory
      name={name}
      url={`/${url.join('/')}`}
  />
</div>
)
```

**Comment by MoHuiTou** [comment]
遇到同样的问题，给加key可以重加载子应用

```
return <MicroAppWithMemoHistory
      name={name}
      url={`/${url.join('/')}`}
      key={name}
  />
```

**Comment by DevXiaolan** [comment]
> 遇到同样的问题，给加key可以重加载子应用
> 
> ```
> return <MicroAppWithMemoHistory
>       name={name}
>       url={`/${url.join('/')}`}
>       key={name}
>   />
> ```

我已经提了PR了，实际上是useEffect里，没有deps到name
https://github.com/umijs/plugins/pull/438
