### ISSUE TITLE
谷歌统计升级到GA4 以后  @umijs/plugin-analytics 不能正常工作，没有统计数据

### ISSUE THREAD

**Issue by Gzbox** [umijs/plugins#443]
谷歌统计升级到GA4 以后  @umijs/plugin-analytics 不能正常工作，没有统计数据
@xiaohuoni

**Comment by xiaohuoni** [comment]
@Gzbox GA4 是一定要升级的吗？

**Comment by Gzbox** [comment]
@xiaohuoni 不是一定要升级 ， 只是我升级完以后发现不能用了，然后也不能退回到升级之前的版本，新创建的媒体资源也是默认GA4。
我有一个另外的网站  用常规的方式，在head 加 script 的方式 来统计，我也升级了，升级之前和升级之后  数据统计不受影响

**Comment by xiaohuoni** [comment]
那是什么差异？

**Comment by xiaohuoni** [comment]
@Gzbox 你看下，和你添加的有什么差异
https://github.com/umijs/plugins/blob/d75f153fba0098005a32e74da95c1f3e761de9bb/packages/plugin-analytics/src/index.ts#L32

**Comment by Gzbox** [comment]
@xiaohuoni 好的我晚会看看，非常感谢哈 👍

**Comment by Gzbox** [comment]
@xiaohuoni  我刚刚看了下  我升级之前和升级之后依然正常使用的那个项目
发现了差异  我使用的是 gtag.js   引入的方式也是官方的  gtag.js 引入方式
```
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-M3LQ38D24L');
</script>
```
你的是 analytics.js ,使用的是analytics 的引入方式

**Comment by Gzbox** [comment]
> @Gzbox 你看下，和你添加的有什么差异
> https://github.com/umijs/plugins/blob/d75f153fba0098005a32e74da95c1f3e761de9bb/packages/plugin-analytics/src/index.ts#L32-L49

是否考虑升级到 gtag.js ？还是说使用analytics.js是有其他考量？

**Comment by Gzbox** [comment]
> @xiaohuoni 我刚刚看了下 我升级之前和升级之后依然正常使用的那个项目
> 发现了差异 我使用的是 gtag.js 引入的方式也是官方的 gtag.js 引入方式
> 
> ```
> <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXX"></script>
> <script>
>   window.dataLayer = window.dataLayer || [];
>   function gtag(){dataLayer.push(arguments);}
>   gtag('js', new Date());
>   gtag('config', 'G-XXXXXX');
> </script>
> ```
> 
> 你的是 analytics.js ,使用的是analytics 的引入方式

至于为啥升级到GA4之后analytics.js不能正常工作  我不清楚😜
是否考虑升级到 gtag.js ？还是说使用analytics.js是有其他考量？

**Comment by xiaohuoni** [comment]
@chenshuai2144 这是什么考量？😜

**Comment by xiaohuoni** [comment]
@chenshuai2144 每日提醒

**Comment by Gzbox** [comment]
> @chenshuai2144 每日提醒

**Comment by Gzbox** [comment]
靠 我点错了，给关闭了。。。。。 @xiaohuoni

**Comment by Gzbox** [comment]
靠。刚点错了给关闭了   😝

**Comment by xiaohuoni** [comment]
@Gzbox 看来帅哥没看信息，我感觉你可以先来个PR

**Comment by Gzbox** [comment]
@xiaohuoni 修改了下引入方式提了一个[455](https://github.com/umijs/plugins/pull/455#issue-524623531)

**Comment by larrygogo** [comment]
没有后续了吗？

**Comment by yiqiang19960302** [comment]
@xiaohuoni 这个可以改到支持ga4 的版本吗
