### ISSUE TITLE
ssr下的qiankun如何使用， window is not defined

### ISSUE THREAD

**Issue by ibandeng** [umijs/plugins#461]
![微信截图_20201201170158](https://user-images.githubusercontent.com/47233643/100718960-f3315500-33f6-11eb-8612-304c737e7a91.png)

如果同时开启ssr和qiankun,就会报错，ssr也失效了，请问怎么解决，ssr下怎么使用qiankun

![微信截图_20201201170800](https://user-images.githubusercontent.com/47233643/100719680-e9f4b800-33f7-11eb-90ac-7700b67dd4f5.png)

**Comment by ibandeng** [comment]
@kuitos 大佬，有什么解决的办法吗？

**Comment by leeguooooo** [comment]
怎么解决的？

**Comment by ibandeng** [comment]
> 怎么解决的？

忘了……过去太久了
