### ISSUE TITLE
plugin-layout 0.13.0 has a breaking update

### ISSUE THREAD

**Issue by gwsbhqt** [umijs/plugins#463]
@chenshuai2144 plugin-layout 0.13.0 has a breaking update. For some reason, I did not use react presets, so plugin-model is not used either. However, this update directly imported plugin-model without judgment, causing the project to fail to start. I hope it can judge whether target exists when importing.
[quote](https://github.com/umijs/plugins/commit/bd61e8ec529facdec3e79579a3a11258d52cbab3#diff-4ee610f4da3c0e57c2bab942697e98418b1fd1ac155f24511cecf4602a233b7aR167)

**Comment by chenshuai2144** [comment]
Give me a repo

**Comment by joesdu** [comment]
> Give me a repo

0.13.2会报错
 yarn start
Starting the development server...

× Webpack
  Compiled with some errors in 38.26s

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                                                                              下午4:49:50

This relative module was not found:

* ../plugin-layout/layoutExports in ./src/.umi/core/umiExports.ts

**Comment by chenshuai2144** [comment]
https://www.npmjs.com/package/@umijs/plugin-layout

try  0.13.3

**Comment by gwsbhqt** [comment]
nice job, it works for me
