### ISSUE TITLE
请问umi2.0的项目怎么用插件改成微前端？

### ISSUE THREAD

**Issue by WentaoHou** [umijs/plugins#510]
我的项目是umi2.0的，我安装了@umijs/plugin-qiankun插件，启动的时候报错，然后试了@umijs/plugin-qiankun@umi2，也是报错，请问能不能用qiankun框架直接改umi的项目？目前我在用qiankun改umi的项目的时候遇到的问题是，没法重写ReactDom.render()，因为umi的项目没有入口文件；

**Comment by WentaoHou** [comment]
![image](https://user-images.githubusercontent.com/37180194/104611058-aad8a880-56bf-11eb-8055-ac3ac9df3fd5.png)
我在子应用里使用umi的qiankun插件，启动时报这个错

**Comment by stack-wuh** [comment]
解决了吗， 太坑了，上来就保存

**Comment by WorkingNiu** [comment]
先升级umi3

**Comment by WentaoHou** [comment]
@stack-wuh @WorkingNiu 已经解决了，子应用是umi2.0的项目可以用 @umi/plugin-qiankun@1.7.0 这个版本，但是umi一定要升到v2.12.0，不敢升到umi3.0，怕不谦容2.0

**Comment by WentaoHou** [comment]
![image](https://user-images.githubusercontent.com/37180194/106129947-ba65f000-619b-11eb-895a-7bb007a0ec68.png)
