### ISSUE TITLE
[RFC]@umijs/plugin-qiankun 2.18.3 页面标题设置异常

### ISSUE THREAD

**Issue by weien601** [umijs/plugins#511]
我遇到的问题是使用qiankun后修改title比较混乱
重现方式：使用 @umijs/plugin-qiankun/example 的代码
1. 给 app1、app2、app3的页面文件都设置上标题
2. 首次进入能够正常展示
3. 但是频繁切换会出现使用了上一个页面的标题或者设置不成功的情况

请问有没有 umi 框架下 qiankun 子项目设置标题的实践方案？

**Comment by kuitos** [comment]
标题需要子应用自己通过 js 设置，或者主应用读取子应用的配置帮他设置
