### ISSUE TITLE
[Bug]主应用app.tsx中导出useQiankunStateForSlave报错 register failed

### ISSUE THREAD

**Issue by 942368681** [umijs/plugins#530]
app.tsx 原代码

`
export function useQiankunStateForSlave() {
    const [globalState, setQiankunGlobalState] = useState({ str: 'aaa' })
    return {
        globalState,
        setQiankunGlobalState
    };
}
`
报错信息
Uncaught Error: register failed, invalid key useQiankunStateForSlave from plugin D:/项目/umi-qiankun-demo/mainApp/src/app.tsx.

**Comment by kuitos** [comment]
无法复现，可参照 [example](https://github.com/umijs/plugins/tree/master/packages/plugin-qiankun/examples/master)，提供可复现仓库后可 reopen issue

**Comment by wy-ang** [comment]
src/app.tsx
`
export function useQiankunStateForSlave() {
  const [globalState, setQiankunGlobalState] = useState({});
  return {
    globalState,
    setQiankunGlobalState,
  };
}
`
报错信息
`Error: register failed, invalid key useQiankunStateForSlave from plugin D:/dev/react/data_visualization_platform/src/app.tsx.`

**Comment by zhuxiujuanz** [comment]
我也遇到了同样的问题，这是为什么啊

**Comment by wei53881** [comment]
重启下试试，我是重启后解决了。
