### ISSUE TITLE
useModel 管理的数据，刷新页面就没了

### ISSUE THREAD

**Issue by wcl-git** [umijs/plugins#550]
useModel 管理的数据，刷新页面就没了，有没有配置方案

**Comment by xiaohuoni** [comment]
useModel 并不是一个数据持久化方案，你需要了解其他的数据持久化方案，来实现你的目的。

**Comment by 895433995** [comment]
现在全局的useModel，切换路由后点击浏览器的返回，数据也是会被重置的吗

**Comment by xiaohuoni** [comment]
> 现在全局的useModel，切换路由后点击浏览器的返回，数据也是会被重置的吗

应该是保留的才对。如果你发现新的问题，可以再发个issues，并附上重现的demo

**Comment by 895433995** [comment]
> > 现在全局的useModel，切换路由后点击浏览器的返回，数据也是会被重置的吗
> 
> 应该是保留的才对。如果你发现新的问题，可以再发个issues，并附上重现的demo

不好意思，是我弄错了，后来发现有个组件维护了状态
