### ISSUE TITLE
MicroApp 加载子应用后不渲染

### ISSUE THREAD

**Issue by njleonzhang** [umijs/plugins#576]
重现项目： https://github.com/njleonzhang/qiankun-study

主应用
```
import { MicroApp } from 'umi'

function list(props) {
  return (
    <div>
      I am user list, I am in main project
      <MicroApp name='list'></MicroApp>
    </div>
  )
}

export default list
```

主应用配置：
```
  qiankun: {
    master: {
      prefetch: 'all',
      // 注册子应用信息
      apps: [
        {
          name: 'list', // 唯一 id
          entry: '//localhost:7001', // html entry
        },
      ],
    },
  },
```

子应用：

```
import React from 'react'

export default function index() {
  return (
    <div>
      I am list index
    </div>
  )
}
```

子应用配置
```
qiankun: {
  slave: {},
},
```

子应用的生命周期可以执行，但是页面没有渲染出来。

文档里有提到：
> 建议使用这种方式来引入不带路由的子应用。 否则请自行关注微应用依赖的路由跟当前浏览器 url 是否能正确匹配上，否则很容易出现微应用加载了，但是页面没有渲染出来的情况。

看起来我似乎是触发了这个场景，`不带路由的子应用`如何理解呢？什么是不带路由的子应用？我的子应用是umi 直接生成的。

**Comment by njleonzhang** [comment]
with this commit, I can workaround the issue, but anyone can help to explain? the `base` props is not mentioned in the document.  

https://github.com/njleonzhang/qiankun-study/commit/857853eae732d2b2e683e5719f0fa5642a12056d

**Comment by njleonzhang** [comment]
`MicroAppWithMemoHistory` 组件也不能按预期的工作，是否能出文档介绍下其参数。

**Comment by kuitos** [comment]
不带路由指的是没有路由系统的子应用。

含路由系统的，用路由绑定的方式关联微应用 https://umijs.org/zh-CN/plugins/plugin-qiankun#a-%E4%BD%BF%E7%94%A8%E8%B7%AF%E7%94%B1%E7%BB%91%E5%AE%9A%E7%9A%84%E6%96%B9%E5%BC%8F
