### ISSUE TITLE
[Bug] safari下locale.baseNavigator配置中文失效

### ISSUE THREAD

**Issue by jxbb** [umijs/plugins#579]
## What happens?

safari下 `navigator.language` 返回 "zh-cn" (而不是'zh-CN')，导致变成默认英文

## Context

- **Umi Version**: 3.4.7
- **Platform**: safari 14.0.2

**Comment by xiaohuoni** [comment]
https://github.com/umijs/plugins/issues/173

**Comment by jxbb** [comment]
可以通过运行时配置自己做映射解决

https://umijs.org/zh-CN/plugins/plugin-locale#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE
