### ISSUE TITLE
主应用非umi，是qiankun主应用，子应用是umi3，可以接入么

### ISSUE THREAD

**Issue by victorWuxz** [umijs/plugins#582]
主应用非umi，是qiankun主应用，子应用是umi3，可以接入么

**Comment by kuitos** [comment]
可以

**Comment by baidongying** [comment]
> 主应用非umi，是qiankun主应用，子应用是umi3，可以接入么

我也遇到这个问题了， 按照插件方式，导出了生命周期钩子，但是一直报 application 'subapp-sydc' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in subapp-sydc entry，请问楼主解决了吗

**Comment by thiennhan2310** [comment]
how can I achieve this. Can not find examples

**Comment by WuBin88996** [comment]
> > 主应用非umi，是qiankun主应用，子应用是umi3，可以接入么
> 
> 我也遇到这个问题了， 按照插件方式，导出了生命周期钩子，但是一直报 application 'subapp-sydc' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in subapp-sydc entry，请问楼主解决了吗



> > 主应用非umi，是qiankun主应用，子应用是umi3，可以接入么
> 
> 我也遇到这个问题了， 按照插件方式，导出了生命周期钩子，但是一直报 application 'subapp-sydc' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in subapp-sydc entry，请问楼主解决了吗

请问这个问题后来怎么解决的 我这边主应用是umi子应用是JQ 子应用全部是运行时动态注册的 现在也是报这个错
