### ISSUE TITLE
plugin @umijs/plugin-dva is already registered by [Path]/node_modules/@umijs/plugin-dva/lib/index.js, plugin from [Path]/node_modules/@umijs/plugin-dva/lib/index.js register failed.

### ISSUE THREAD

**Issue by KineticDog** [umijs/plugins#596]
Hi there. I'm recently playing with umijs from scratch and get stuck at a very beginning point. I can't setup dvajs inside umijs project.
The steps to regenerate the issue:
1. Create a umijs project structure: `yarn create @umijs/umi-app`
2. Install @umijs/plugin-dva: `npm install @umijs/plugin-dva`
3. Add dva configuration into '.umirc.ts': `  dva: {
    immer: true,
    hmr: false,
  },`
4. Start base project: `npm start`
Then this error would appear. I would like to know how to fix this issue

**Comment by hendiko** [comment]
I have the same problem, I used umijs3, I installed @umijs/plugin-dva, then problem ocurred.

**Comment by xiaohuoni** [comment]
https://github.com/umijs/plugins/issues/683
