### ISSUE TITLE
`@umijs/openapi` 是开源的吗？

### ISSUE THREAD

**Issue by lcysgsg** [umijs/plugins#630]
[https://www.npmjs.com/package/@umijs/plugin-openapi](https://www.npmjs.com/package/@umijs/plugin-openapi) 文档里提到的网站 [https://umijs.org/plugins/plugin-openapi](https://umijs.org/plugins/plugin-openapi) 打不开

[`@umijs/openapi`](https://www.npmjs.com/package/@umijs/openapi) 没有仓库地址，是不开源的吗？ 生成代码有些问题，比如调文件接口需要传 `blob` 但生成代码里的判断是当作 `object` 进行了 `JSON.stringify` 导致上传接口不能正常使用

```ts
// 生成的请求代码
export async function uploadImage(
  body: {
    imgFile?: string;
  },
  options?: { [key: string]: any },
) {
  const formData = new FormData();

  Object.keys(body).forEach((ele) => {
    const item = (body as any)[ele];

    if (item !== undefined && item !== null) {
      formData.append(ele, typeof item === 'object' ? JSON.stringify(item) : item);
    }
  });

  return request<API.JsonResult>('/api/image/uploadImage', {
    method: 'POST',
    headers: {
      'Content-Type': 'multipart/form-data',
    },
    data: formData,
    ...(options || {}),
  });
}
```

**Comment by lahvey** [comment]
希望能开源，是非常好用的工具，但是遇到好些问题一直没法解决，又没法提交更新

**Comment by kaisawind** [comment]
openAPI 仓库
https://github.com/chenshuai2144/openapi2typescript

**Comment by kaisawind** [comment]
问题很多，相当多

**Comment by kaisawind** [comment]
@lcysgsg
可以自定义request内容

```js
uploadImage({}, {}, {requestType: 'blob', data: imgFile})
```

**Comment by lcysgsg** [comment]
> openAPI 仓库
> https://github.com/chenshuai2144/openapi2typescript

厉害啊，这都找到了！

> 问题很多，相当多

fork fork gogogo :P
 

> @lcysgsg
> 可以自定义request内容
> 
> ```js
> uploadImage({}, {}, {requestType: 'blob', data: imgFile})
> ```

nice 可怜我都没发现能这样传参数
