### ISSUE TITLE
plugin @umijs/plugin-dva is already registered 

### ISSUE THREAD

**Issue by yanglvyou** [umijs/plugins#683]
umi 使用 @umijs/plugin-dva 报错

1. yarn create @umijs/umi-app；
2. yarn add @umijs/plugin-dva;
3. '.umirc.ts' : dva: { immer: true, hmr: false, }；
4. yarn start 时报错。

<img width="1794" alt="WeChatcdaaf1225badf5368decbf2c8e0058de" src="https://user-images.githubusercontent.com/40206669/129642115-b9142a65-3e6e-4bd0-87b1-10900329edaa.png">

"dependencies": {
    "@ant-design/pro-layout": "^6.5.0",
    "@umijs/plugin-dva": "^0.13.0",
    "cross-env": "^7.0.3",
    "react": "17.x",
    "react-dom": "17.x",
    "umi": "^3.5.17"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.5.17",
    "lint-staged": "^10.0.7",
    "prettier": "^2.2.0",
    "typescript": "^4.1.2",
    "yorkie": "^2.0.0"
  }

**Comment by hendiko** [comment]
I have the same problem, how to resolve it?

**Comment by xiaohuoni** [comment]
```
yarn add @umijs/plugin-dva;
```
这步骤不需要，插件集里面已经有 dva 了

**Comment by LoveEocding** [comment]
使用plugin-layout 设置布局以后改变 primaryColor  整体主题 无效

**Comment by Aomd** [comment]
可以试试 把 @umijs/preset-react 依赖删除
