### ISSUE TITLE
[BUG] plugin-locale 尝试 import {useIntl} from 'umi' 报错

### ISSUE THREAD

**Issue by tolbkni** [umijs/plugins#71]
```typescript
import { useIntl } from 'umi';
```
构建时提示 `"export 'useIntl' was not found in 'umi'`

plugin-locale 版本是 0.3.0

**Comment by tolbkni** [comment]
解决了，需要在 `.umirc.ts' 中添加 `locale: {}` 的配置项

**Comment by gaoxianglyx** [comment]
> 解决了，需要在 `.umirc.ts' 中添加 `locale: {}` 的配置项

能否发一下这个文件？我本地没有发现又.umirc.ts 这个文件呢？

**Comment by tolbkni** [comment]
参考官方模板 [.umirc.ts.tpl](https://github.com/umijs/umi/blob/master/packages/create-umi-app/templates/AppGenerator/.umirc.ts.tpl)

**Comment by wangfupeng1988** [comment]
- `config/config.ts` 中增加 `locale: {}`
- 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
- 重启服务

当前版本 `"umi": "^3.2.22"`
