### ISSUE TITLE
@umijs/plugin-request功能bug

### ISSUE THREAD

**Issue by starsoft35** [umijs/plugins#74]
@umijs/plugin-request插件的构建时配置和运行时配置均不起作用，我按照文档示例配置如下：

import { RequestConfig } from 'umi';

export const request: RequestConfig = {
  timeout: 1000,
  errorConfig: {},
  middlewares: [],
};
运行时配置不起作用

**Comment by yutingzhao1991** [comment]
是哪个配置无效？怎么使用的？能否提供下最下复现的仓库代码看看。

**Comment by hzgotb** [comment]
> 是哪个配置无效？怎么使用的？能否提供下最下复现的仓库代码看看。

umi/core/plugin.ts 没有注册到 request

**Comment by calefy-chen** [comment]
同问，src/app.ts 里面配置如prefix，在调用时，并没有添加上运行时配置的内容

**Comment by yutingzhao1991** [comment]
修复了 https://github.com/umijs/plugins/pull/86
