### ISSUE TITLE
@umijs/plugin-dva

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/plugins#89]
![image](https://user-images.githubusercontent.com/8001457/76674376-b82d8e00-65e9-11ea-8e87-627fea108eb3.png)
生成的connect.ts loading models key出错，要加“”。
用文件名做key不太合理 。都是用model做文件名了，一大堆重复的
![image](https://user-images.githubusercontent.com/8001457/76674543-97fece80-65eb-11ea-9a5d-75e35760419a.png)

**Comment by sorrycc** [comment]
@xiaohuoni
