### ISSUE TITLE
@umijs/plugin-request新问题

### ISSUE THREAD

**Issue by starsoft35** [umijs/plugins#90]
@umijs/plugin-request由于封装一层在异步调用后初始化相关方法，导致以前的request.get(url[, options])、request.post(url[, options])、request.delete(url[, options])、request.patch(url[, options])等快捷方法无法使用，最致命的就是request.interceptors.request.use这无法使用了

**Comment by tli4** [comment]
+1 request.interceptors.request.use 不能用挺致命的，很多业务升不上来就是因为要在 interceptor 里做未登陆跳转之类的通用处理

**Comment by yutingzhao1991** [comment]
这个不是预期要暴露的功能，可以使用运行时里面的 `middlewares` 替代。

**Comment by yutingzhao1991** [comment]
不过可以考虑支持 `interceptors` 配置。
