### ISSUE TITLE
plugin request 配置app.ts没有生效

### ISSUE THREAD

**Issue by fangaofeng** [umijs/plugins#92]
umi 3.0.8
```
export const request: RequestConfig = {
  timeout: 6000,
  prefix: '/api',
  errorConfig: {
    adaptor: resData => {
      console.log('resData', resData);
      return {
        data: resData.data,
        success: resData.status === 'ok',
        errorMessage: resData.message,
      };
    },
  },
  middlewares: [],
};
```
执行代码，
```
 const data = await request<ArticleItem[]>('/blog/article', {
        params: {
          page: params.current,
          size: params.pageSize,
        },
      });
```
结果：
data 仍然是resData，没有success

**Comment by yutingzhao1991** [comment]
`adaptor` 是是用来适配错误信息的，不会影响实际数据格式。

why：避免影响到 TypeScript 的推断。

另外建议使用 `useRequest`，这样可以直接获取到 `data`，少转一层。

**Comment by shusheng888** [comment]
我的解决办法是
`
        request={async (params)=>{
          console.log('paramsparamsparams',params)
          const res = await getUserList(params)
          console.log('res______>',res)
          return {
            total: res.total,
            data: res.rows,
          }
        }}
`
如果你的后端接口格式里面没有data字段，或者改动较大 就像我这个 后端返回的主要数据存在在rows字段里面的话，那你可以在使用ProTable这个组件的时候 进行手动格式转换
