### ISSUE TITLE
基座应用 umi3，子应用 umi4，二者均使用 @umijs/plugin-qiankun 是否有不兼容的风险？

### ISSUE THREAD

**Issue by hoperyy** [umijs/plugins#935]
@umijs/plugin-qiankun 文档中没有描述这类问题，如果有风险的话，希望给下风险描述。

**Comment by kuitos** [comment]
兼容的

**Comment by mirages** [comment]
umi4 怎么使用 qiankun 呢？使用 @umijs/plugin-qiankun 插件报错 `@umijs/plugin-qiankun/lib/master/utils.js:53:23` Cannot read properties of undefined (reading 't')
