### ISSUE TITLE
建议plugin-qiankun和qiankun保持同步，怎加自定义fetch请求

### ISSUE THREAD

**Issue by AkiSong** [umijs/plugins#949]
目前项目改了鉴权方式，需要在请求头中加签，plugin-qiankun不支持自定义fetch，导致请求失败。
希望开发组同步qiankun的该功能
![image](https://github.com/umijs/plugins/assets/40135149/c365a974-82c6-4397-94fc-3eb4a76709f6)
![image](https://github.com/umijs/plugins/assets/40135149/64ba544a-eea1-4a45-93ea-2f030e9786fb)

**Comment by kuitos** [comment]
支持的，app.ts 里的 qiankun 配置里直接写
