### ISSUE TITLE
qiankun父应用进入微应用，微应用的路由一直作用在夫应用上

### ISSUE THREAD

**Issue by HLDipsy** [umijs/plugins#970]
父应用进入微应用，微应用的路由一直作用在夫应用上，先匹配微应用的路由，在匹配父应用的路由
父应用： umi3 + @umijs/plugin-qiankun
父应用config配置：
![fe67cf40261dc1c19fbdd8ee96fbd27](https://github.com/umijs/plugins/assets/112858085/e8adf4b8-217f-4974-ac22-fd38b51a0b75)
父应用路由配置：
![fbfca6ce4fb576eeaa8c6b5c76be4fe](https://github.com/umijs/plugins/assets/112858085/88b13dc4-3c49-430a-9af5-192d46128dcc)

微应用：vite+dva+react，使用 vite-plugin-legacy-qiankun 
微应用入口文件：
![3dfb490b61529539bd3577a72ade34c](https://github.com/umijs/plugins/assets/112858085/60e68139-5001-4b0a-a84e-f256dac92e4d)

报错：进入过微应用，微应用路由就会存在，跳转父应用的路由时，会提示路由404（子路由未匹配到父应用的路由），每进入一次提示就会累加一次，例如进入五次微应用，在点击父应用的路由，会提示报错五次路由404

**Comment by PeachScript** [comment]
看描述路由 404 是微应用报的，和 `@umijs/plugin-qiankun` 应该无关，请自行检查实现，比如 unmount 是否正常销毁应用实例、lifecycle 是否正常工作以及 `vite-plugin-legacy-qiankun`（非 UmiJS 团队维护）是否如预期工作，issue closed

如果排查下来确定和 `@umijs/plugin-qiankun` 有关，可以补充最小可复现仓库，再重新 reopen

**Comment by HLDipsy** [comment]
> 看描述路由 404 是微应用报的，和 `@umijs/plugin-qiankun` 应该无关，请自行检查实现，比如 unmount 是否正常销毁应用实例、lifecycle 是否正常工作以及 `vite-plugin-legacy-qiankun`（非 UmiJS 团队维护）是否如预期工作，issue closed
> 
> 如果排查下来确定和 `@umijs/plugin-qiankun` 有关，可以补充最小可复现仓库，再重新 reopen

@umijs/plugin-qiankun  可以手动关闭子应用实例吗
